---
# Sets up the backend servers by copying over the hillview server jars
- hosts: backends
  tasks:
    - name: Create directory
      file:
          path: hillview
          state: directory
          mode: 0755
    - name: Copy files
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
              - {src: '../platform/target/hillview-server-jar-with-dependencies.jar', dest: 'hillview'}


# Sets up the web server by first downloading tomcat, and updating the ROOT war with the Hillview Web server war.
- hosts: web
  tasks:
    - name: Load variables from configuration file
      include_vars: config.yaml

    - stat:
        path: apache-tomcat-8.5.8
      register: p

    - debug:
         msg: "Path exists and isn't a symlink"
      when: p.stat.isdir is not defined and p.stat.isdir == False

    - name: Download Tomcat
      shell: wget http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.8/bin/apache-tomcat-8.5.8.tar.gz
      when: p.stat.isdir is not defined and p.stat.isdir == False

    - name: Untar Tomcat
      shell: tar -xzvf apache-tomcat-8.5.8.tar.gz; rm -rf apache-tomcat-8.5.8.tar.gz;
      when: p.stat.isdir is not defined and p.stat.isdir == False

    - name: Remove previous ROOT and ROOT.war
      shell: rm -rf apache-tomcat-8.5.8/webapps/ROOT; rm -rf apache-tomcat-8.5.8/webapps/ROOT.war
      when: p.stat.isdir is not defined and p.stat.isdir == False

    - name: Copy files
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
              - {src: '../web/target/web-1.0-SNAPSHOT.war', dest: 'apache-tomcat-8.5.8/webapps/ROOT.war'}
    - name: ensure file exists
      copy:
        content: ""
        dest: ~/serverlist
        force: no
        mode: 0755

    - name: Create backend file list
      lineinfile: dest=serverlist line="{{item}}:{{ backend_port }}"
      with_items: "{{ groups.backends }}"
