---
- hosts: backends
  tasks:
   - name: Load variables from configuration file
     include_vars: config.yaml

   - name: Stop backends
     shell: jps -v | grep "hillview-server" | awk '{print $1}' | xargs -r kill

- hosts: web
  tasks:
   - name: Load variables from configuration file
     include_vars: config.yaml

   - name: Stop web server
     shell:
        cmd: "{{tomcat}}/bin/shutdown.sh"
        chdir: "{{service_folder}}"
