#!/bin/bash

RED='\033[0;31m' # Red Color
NC='\033[0m' # No Color
printf "#### ${RED}Executing pre-commit hook${NC} ####\n"
printf "#### ${RED}Running 'mvn clean test' for errors${NC} ####\n"
echo ""

# retrieving current working directory
CWD=`pwd`
MAIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# go to main project dir
cd $MAIN_DIR/../../

# running maven clean test
mvn clean test
if [ $? -ne 0 ]; then
  echo ""
  printf "#### ${RED}Aborting commit because 'mvn clean test' did not succeed. Please fix the errors and retry.${NC} ####\n"
  # go back to current working dir
  cd $CWD
  exit 1
fi

# go back to current working dir
cd $CWD
