#!/usr/bin/env python3

"""This python program generate a csv data for Cassandra based on 
 data/ontime/2016_1.csv. The difference is that the new csv data will 
 contain a unique primary key as it's first field. The generated file
 will be stored at data/sstable/flights_data.csv"""

import sys

# The number of rows that will be generated by this script
num_of_rows = 100

def addPrimaryKey():
  with open('flights_data.csv', 'w') as output:
      sys.stdout = output

      with open("../ontime/2016_1.csv") as fp:
         header = fp.readline()
         print("ID," + header, end = '')
         cnt = 0
         line = fp.readline()
         while cnt < num_of_rows:
             print(str(cnt) + "," + line, end = '')
             line = fp.readline()
             cnt += 1

def main():
    """Main function"""
    addPrimaryKey()

if __name__ == "__main__":
    main()